import { Ejercicio } from "./ejercicio";

export const EJERCICIOS: Ejercicio[]=[
  {id:1, name:'Flexion', description: 'Flexiones hkdhalsd nkjhkj , un mdsekihsdfm . nkojhkjl. Mahsuyyhdsslkj n bkjhg m jhkhjkjhu !!!! lorem. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Officia perspiciatis autem, iure voluptas corporis ad praesentium sint fugit libero iusto recusandae ea vel. Error consectetur possimus veniam non, rem minus!Lorem ipsum dolor sit, amet consectetur adipisicing elit. Officia perspiciatis autem, iure voluptas corporis ad praesentium sint fugit libero iusto recusandae ea vel. Error consectetur possimus veniam non, rem minus!',autor:'Kiare Jusy'},
  {id:2, name:'Sentadilla', description: 'Flexiones 3232. iones hkdhalsd nkjhkj , un mdsekihsdfm . nkojhkjl. Mahsuyyhdsslkj n bkjhg m jhkhjkjhu !!!! lorem. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Officia perspiciatis autem, iure voluptas corporis ad praesentium sint fugit libero iusto recusandae ea vel. Error consectetur possimus veniam non, rem minus!Lorem ipsum dolor sit, amet consectetur adipisicing elit. Officia perspiciatis autem, iure voluptas corporis ad praesentium sint fugit libero iusto recusandae ea vel. Error consectetur possimus veniam non, rem minus',autor:'Hausy Lussi'},
  {id:3, name:'Skills', description: 'Habilidades. 87687. iones hkdhalsd nkjhkj , un mdsekihsdfm . nkojhkjl. Mahsuyyhdsslkj n bkjhg m jhkhjkjhu !!!! lorem. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Officia perspiciatis autem, iure voluptas corporis ad praesentium sint fugit libero iusto recusandae ea vel. Error consectetur possimus veniam non, rem minus!Lorem ipsum dolor sit, amet consectetur adipisicing elit. Officia perspiciatis autem, iure voluptas corporis ad praesentium sint fugit libero iusto recusandae ea vel. Error consectetur possimus veniam non, rem minus',autor:'Kiare Jusy'},
  {id:4, name:'Aficiones', description:'Vida real. iones hkdhalsd nkjhkj , un mdsekihsdfm . nkojhkjl. Mahsuyyhdsslkj n bkjhg m jhkhjkjhu !!!! lorem. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Officia perspiciatis autem, iure voluptas corporis ad praesentium sint fugit libero iusto recusandae ea vel. Error consectetur possimus veniam non, rem minus!Lorem ipsum dolor sit, amet consectetur adipisicing elit. Officia perspiciatis autem, iure voluptas corporis ad praesentium sint fugit libero iusto recusandae ea vel. Error consectetur possimus veniam non, rem minus',autor:'Lissus Ausns'},
  {id:5, name:'Definiciones', description: 'Puntos de vista. iones hkdhalsd nkjhkj , un mdsekihsdfm . nkojhkjl. Mahsuyyhdsslkj n bkjhg m jhkhjkjhu !!!! lorem. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Officia perspiciatis autem, iure voluptas corporis ad praesentium sint fugit libero iusto recusandae ea vel. Error consectetur possimus veniam non, rem minus!Lorem ipsum dolor sit, amet consectetur adipisicing elit. Officia perspiciatis autem, iure voluptas corporis ad praesentium sint fugit libero iusto recusandae ea vel. Error consectetur possimus veniam non, rem minus',autor:'Kusaa Erusk'},
  {id:6, name:'Paises', description: 'Experiencias autenticas iones hkdhalsd nkjhkj , un mdsekihsdfm . nkojhkjl. Mahsuyyhdsslkj n bkjhg m jhkhjkjhu !!!! lorem. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Officia perspiciatis autem, iure voluptas corporis ad praesentium sint fugit libero iusto recusandae ea vel. Error consectetur possimus veniam non, rem minus!Lorem ipsum dolor sit, amet consectetur adipisicing elit. Officia perspiciatis autem, iure voluptas corporis ad praesentium sint fugit libero iusto recusandae ea vel. Error consectetur possimus veniam non, rem minus',autor:'Kiare Jusy'}
];
